# -*- coding: utf-8 -*-
"""contract_entity_extractor.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19mqMSqPeThTeBZj64sbmDxX_So3f_pS8
"""

import spacy

nlp = spacy.load("en_core_web_sm")

text = """
This Agreement is made on 15th July 2025 between Infosys Limited
(hereinafter referred to as "Vendor") and ABC Corp (hereinafter referred to as "Client").
The effective date of this contract shall be 1st August 2025.
The contract value is $500,000 for IT consulting services.
"""

doc = nlp(text)

extracted = {
    "Contract Date": None,
    "Effective Date": None,
    "Contract Value": None,
    "Vendor": None,
    "Client": None
}

for ent in doc.ents:
    if ent.label_ == "DATE" and extracted["Contract Date"] is None:
        extracted["Contract Date"] = ent.text
    elif ent.label_ == "DATE" and extracted["Effective Date"] is None and extracted["Contract Date"] is not None:
        extracted["Effective Date"] = ent.text
    elif ent.label_ == "MONEY":
        extracted["Contract Value"] = ent.text
    elif ent.label_ == "ORG":
        if extracted["Vendor"] is None:
            extracted["Vendor"] = ent.text
        elif extracted["Client"] is None:
            extracted["Client"] = ent.text

print("\n📑 Extracted Contract Information:")
for k, v in extracted.items():
    print(f"{k}: {v}")